-- ========================================
-- 工单测试数据插入脚本
-- 为业主ID=1002添加各种类型的工单
-- ========================================

-- 先清除旧的测试数据
DELETE FROM `work_order` WHERE `submitter_id` = 1002;

-- 插入测试工单数据
INSERT INTO `work_order` (
    `order_no`,
    `title`,
    `content`,
    `category`,
    `priority`,
    `status`,
    `submitter_id`,
    `assignee_id`,
    `room_id`,
    `images`,
    `submit_time`,
    `assign_time`,
    `start_time`,
    `complete_time`,
    `rating`,
    `feedback`,
    `cost`,
    `create_time`,
    `update_time`,
    `deleted`
) VALUES

-- 1. 待处理的水电报修工单
('WO202509300001', 
 '厨房水龙头漏水', 
 '厨房洗菜盆的水龙头一直在滴水，已经持续了两天，请尽快安排维修师傅处理。水龙头是旋转式的，可能是密封圈老化导致的。', 
 'REPAIR',
 'MEDIUM',
 'PENDING',
 1002,              -- 业主ID=1002提交
 NULL,              -- 尚未分配维修师傅
 1,                 -- 关联房屋ID=1
 '[]',
 NOW() - INTERVAL 2 HOUR,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NOW() - INTERVAL 2 HOUR,
 NOW() - INTERVAL 2 HOUR,
 0),

-- 2. 处理中的空调报修工单
('WO202509290001', 
 '客厅空调不制冷', 
 '客厅的空调开机后只吹风不制冷，可能是缺氟或者压缩机有问题。天气越来越热，希望尽快维修。', 
 'REPAIR',
 'HIGH',
 'PROCESSING',
 1002,
 1001,              -- 已分配给维修师傅ID=1001
 1,
 '[]',
 NOW() - INTERVAL 1 DAY,
 NOW() - INTERVAL 1 DAY + INTERVAL 1 HOUR,
 NOW() - INTERVAL 20 HOUR,
 NULL,
 NULL,
 NULL,
 NULL,
 NOW() - INTERVAL 1 DAY,
 NOW() - INTERVAL 20 HOUR,
 0),

-- 3. 已完成的门锁报修工单（待评价）
('WO202509280001', 
 '入户门锁打不开', 
 '今天早上出门时发现门锁很难打开，需要用很大力气才能转动钥匙，担心下次会完全锁死。', 
 'REPAIR',
 'URGENT',
 'COMPLETED',
 1002,
 1001,
 1,
 '[]',
 NOW() - INTERVAL 2 DAY,
 NOW() - INTERVAL 2 DAY + INTERVAL 30 MINUTE,
 NOW() - INTERVAL 2 DAY + INTERVAL 1 HOUR,
 NOW() - INTERVAL 2 DAY + INTERVAL 3 HOUR,
 NULL,              -- 尚未评价
 NULL,
 50.00,             -- 维修费用50元
 NOW() - INTERVAL 2 DAY,
 NOW() - INTERVAL 2 DAY + INTERVAL 3 HOUR,
 0),

-- 4. 已评价的网络报修工单
('WO202509270001', 
 '网络信号不稳定', 
 '家里的WiFi信号经常断断续续，特别是在卧室，网速也很慢，影响正常使用。可能是路由器位置不合适或设备老化。', 
 'REPAIR',
 'LOW',
 'COMPLETED',
 1002,
 1001,
 1,
 '[]',
 NOW() - INTERVAL 3 DAY,
 NOW() - INTERVAL 3 DAY + INTERVAL 1 HOUR,
 NOW() - INTERVAL 2 DAY,
 NOW() - INTERVAL 2 DAY + INTERVAL 3 HOUR,
 5,                 -- 满分评价
 '师傅很专业，重新调整了路由器位置并优化了信号配置，现在网络非常稳定！服务态度也很好。',
 80.00,
 NOW() - INTERVAL 3 DAY,
 NOW() - INTERVAL 2 DAY + INTERVAL 3 HOUR,
 0),

-- 5. 待处理的投诉工单
('WO202509290002', 
 '楼道卫生清理不及时', 
 '我们这层楼道已经好几天没有打扫了，地上有明显的灰尘和垃圾，希望物业能够加强楼道卫生管理。', 
 'COMPLAINT',
 'MEDIUM',
 'PENDING',
 1002,
 NULL,
 1,
 '[]',
 NOW() - INTERVAL 10 HOUR,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NOW() - INTERVAL 10 HOUR,
 NOW() - INTERVAL 10 HOUR,
 0),

-- 6. 处理中的咨询工单
('WO202509290003', 
 '停车位租赁咨询', 
 '您好，我想咨询一下地下停车位的租赁事宜，请问现在还有空余停车位吗？月租费是多少？需要什么手续？', 
 'INQUIRY',
 'LOW',
 'PROCESSING',
 1002,
 1000,              -- 物业管理员处理
 1,
 '[]',
 NOW() - INTERVAL 8 HOUR,
 NOW() - INTERVAL 7 HOUR,
 NOW() - INTERVAL 6 HOUR,
 NULL,
 NULL,
 NULL,
 NULL,
 NOW() - INTERVAL 8 HOUR,
 NOW() - INTERVAL 6 HOUR,
 0),

-- 7. 已完成的建议工单
('WO202509280002', 
 '建议增加儿童游乐设施', 
 '小区的儿童游乐设施比较单一，建议能够增加一些适合不同年龄段儿童的游乐设备，比如滑梯、秋千等。这样可以让小区更适合家庭居住。', 
 'SUGGESTION',
 'LOW',
 'COMPLETED',
 1002,
 1000,
 1,
 '[]',
 NOW() - INTERVAL 4 DAY,
 NOW() - INTERVAL 4 DAY + INTERVAL 2 HOUR,
 NOW() - INTERVAL 3 DAY,
 NOW() - INTERVAL 3 DAY + INTERVAL 5 HOUR,
 4,                 -- 4分评价
 '感谢您的建议，物业已将此建议纳入下一年度改造计划中。',
 NULL,
 NOW() - INTERVAL 4 DAY,
 NOW() - INTERVAL 3 DAY + INTERVAL 5 HOUR,
 0),

-- 8. 紧急待处理的电梯报修
('WO202509300002', 
 '电梯异常响声', 
 '3号电梯在运行过程中有异常的"咔咔"响声，声音比较大，担心存在安全隐患。请尽快安排专业人员检查。', 
 'REPAIR',
 'URGENT',
 'PENDING',
 1002,
 NULL,
 1,
 '[]',
 NOW() - INTERVAL 1 HOUR,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NOW() - INTERVAL 1 HOUR,
 NOW() - INTERVAL 1 HOUR,
 0),

-- 9. 已完成的卫生间报修
('WO202509260001', 
 '卫生间下水道堵塞', 
 '卫生间洗手池下水很慢，怀疑是下水道有堵塞。已经尝试用疏通剂处理，但效果不明显。', 
 'REPAIR',
 'HIGH',
 'COMPLETED',
 1002,
 1001,
 1,
 '[]',
 NOW() - INTERVAL 4 DAY,
 NOW() - INTERVAL 4 DAY + INTERVAL 30 MINUTE,
 NOW() - INTERVAL 4 DAY + INTERVAL 1 HOUR,
 NOW() - INTERVAL 4 DAY + INTERVAL 2 HOUR,
 5,
 '师傅很快就到了，用专业工具清理了下水道，现在下水非常通畅。服务很专业！',
 100.00,
 NOW() - INTERVAL 4 DAY,
 NOW() - INTERVAL 4 DAY + INTERVAL 2 HOUR,
 0),

-- 10. 待处理的灯具报修
('WO202509290004', 
 '客厅吊灯不亮', 
 '客厅的吊灯突然不亮了，换了灯泡还是不行，可能是电路或者镇流器的问题。', 
 'REPAIR',
 'MEDIUM',
 'PENDING',
 1002,
 NULL,
 1,
 '[]',
 NOW() - INTERVAL 6 HOUR,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NOW() - INTERVAL 6 HOUR,
 NOW() - INTERVAL 6 HOUR,
 0);

-- 验证插入结果
SELECT 
    order_no AS '工单编号',
    title AS '标题',
    category AS '类别',
    priority AS '优先级',
    status AS '状态',
    submit_time AS '提交时间'
FROM work_order
WHERE submitter_id = 1002 AND deleted = 0
ORDER BY submit_time DESC;
